[project]
name = "mcp-server-runbook"
version = "0.1.0"
description = "A helper tools to config Runbook for MCP Client to run"
readme = "README.md" # Optional: create a README.md file
requires-python = ">=3.12"
license = { text = "MIT" } # Optional: choose a license

authors = [
  { name = "Ralph Tran", email = "ralphtran.sg@gmail.com" },
]

keywords = ["mcp", "mcp-server", "runbook", "builder"] # Optional

dependencies = [
    "pyyaml", # For parsing the input YAML data
]

[dependency-groups]
dev = [
    "black>=24.0.0", # Python code formatter
    "pip>=23.0",     # Package installer (good to have explicitly for venv)
    "pytest>=7.0.0", # For running tests
    "flake8>=7.0.0", # Python linter
    # Add other development tools like linters (e.g., "ruff") here
]

# Example: Add a console script entry point if you build a CLI tool
# [project.scripts]
# resume-build = "resume_builder.cli:main"

# Configuration for tools like Black
[tool.black]
line-length = 88
target-version = ["py313"]

[tool.pytest.ini_options]
pythonpath = ["src"]
